name: Terraform Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

jobs:
  drift-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module-path: ["modules/network", "modules/compute"]

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: ${{ matrix.module-path }}
        run: terraform init -input=false

      - name: Terraform Plan (Detect Drift)
        id: plan
        working-directory: ${{ matrix.module-path }}
        run: |
          set +e
          terraform plan -detailed-exitcode -no-color > plan.txt
          EXIT_CODE=$?
          echo "PLAN_EXIT_CODE=$EXIT_CODE" >> $GITHUB_ENV
          set -e

      - name: Show plan result
        run: echo "Terraform plan exit code ${{ env.PLAN_EXIT_CODE }}"

      - name: Capture plan output
        id: capture
        working-directory: ${{ matrix.module-path }}
        run: |
          echo "PLAN_CONTENT<<EOF" >> $GITHUB_ENV
          cat plan.txt >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Email if Drift Detected
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "Terraform Drift Detected in ${{ matrix.module-path }}"
          to: ${{ secrets.ALERT_EMAIL }}
          from: ${{ secrets.EMAIL_USER }}
          secure: true
          body: |
            Dear Team,

            Drift has been detected in the following Terraform module:
            ${{ matrix.module-path }}

            Exit Code: ${{ env.PLAN_EXIT_CODE }}

            ---------------------------------------------------------------------
            ${{ env.PLAN_CONTENT }}
            ---------------------------------------------------------------------

            Regards,
            Terraform Drift Automation
